### ISSUE TITLE
only merge addresses with buildings if they intersect, else import address points as nodes

### ISSUE THREAD

**Issue by wilsaj** [atx-osg/atx-buildings#14]
We'll have CoA addresses for vacant lots or places where new construction has happened, so we shouldn't throw out addresses that don't intersect a building. Also, buildings with multiple address points should keep their addresses as individual nodes.

**Comment by maxerickson** [comment]
Some degree of fuzziness may be desirable. An example:

http://www.openstreetmap.org/query?lat=30.32261&lon=-97.74731

The node for 2612 is only close to the one building. I think in the past people have just tested for the node being within a few meters of a single building. I guess it would depend on your overall timetable and how much work it would be to adapt the code.
