### ISSUE TITLE
schedule mapping party

### ISSUE THREAD

**Issue by wilsaj** [atx-osg/atx-buildings#18]
Schedule mapping party focused on the import. Need to find:
- [x] space
- [x] food
- [x] drinks

The OSM US board has provided some funds that should cover us, but additional sponsorship is definitely welcome.

Looking at one of the following Saturdays:
- 10/24
- 11/7
- 11/14

**Comment by jseppi** [comment]
I can make 10/24! :tada:

**Comment by wilsaj** [comment]
Found a possible space: Brew & Brew would be nice because good beer & good coffee, but is only available 11/7. Does that work?

**Comment by johnclary** [comment]
I can make 10/24 and 11/7. Probably not 11/14.

...and yes to good beer and good coffee

**Comment by wilsaj** [comment]
How about 11/8 (Sunday)?

**Comment by jseppi** [comment]
:+1:

**Comment by johnclary** [comment]
:thumbsup:

**Comment by wilsaj** [comment]
cool, checking with B&B for that date

**Comment by wilsaj** [comment]
Update: We some have space reserved at brew and brew from noon-5 on 11/8
:tada: :beers: :coffee:  :earth_americas:

**Comment by jseppi** [comment]
:office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :office: :house: :post_office: :arrow_right: :earth_americas:

**Comment by johnclary** [comment]
:+1: 

:computer: :beers:

**Comment by mateoclarke** [comment]
I'm about 50% on whether I'll be able to join but I'd like to promote the OSM Mapping Party through Open Austin's Meetup.com, Email List & Calendar (_unless you want to limit the size of the group_).

**Comment by wilsaj** [comment]
Hey Mateo! I really hope you can make it.

I appreciate your help promoting the mapping party, but I think we should keep this one low-key since the physical space is limited and the import work will be fairly advanced. I don't like excluding anyone, but I also don't think it's feasible to get newcomers to a sufficient level of expertise on the same day without it being overwhelming and unfun.

I'll be at the Open Austin hack night on Nov 3rd and can run a quick onboarding session there if any Open Austiners are interested in working on the import. Would that be cool?

**Comment by wilsaj** [comment]
closing, since this thing is totally happening
