### ISSUE TITLE
figure out the appropriate mapping of source attributes -> OSM tags

### ISSUE THREAD

**Issue by wilsaj** [atx-osg/atx-buildings#2]
Specifically, what tags should we be using to represent the source information:
- building height
- base elevation
- address info
- anything else?

**Comment by claysmalley** [comment]
[address info](http://wiki.openstreetmap.org/wiki/Key:addr) (example used is the HEB at Hancock):
- `addr:housenumber=1000`
- `addr:street=East 41st Street`
- `addr:city=Austin`
- `addr:state=TX`
- `addr:postcode=78751`
- `addr:country=US`

[base elevation:](http://wiki.openstreetmap.org/wiki/Key:ele)
- `ele=171` for a base elevation of 171 meters

[building height:](http://wiki.openstreetmap.org/wiki/Key:height)
- `height=5.5` for a 5.5 meter tall building

[marking a way as a building:](http://wiki.openstreetmap.org/wiki/Key:building)
- `building=yes`

From the wiki, it looks like using feet is possible on building height, but I'd avoid it. Meters seem to be the standard, and it's just some simple math to convert them from feet.

**Comment by wilsaj** [comment]
:+1:  Thanks Clay

**Comment by wilsaj** [comment]
closing - this info has been added to wiki
