### ISSUE TITLE
add postcode tags

### ISSUE THREAD

**Issue by cliffordsnow** [atx-osg/atx-buildings#22]
Please hold off on the import until you have review with the community.

Thanks,
Clifford

**Comment by wilsaj** [comment]
Hi Clifford.

I thought we were good to go with regard to community review. See the thread on import-us mailing list at: https://lists.openstreetmap.org/pipermail/imports-us/2015-September/000722.html

We do not have city or postcode tags because they were not part of the imported dataset.

**Comment by cliffordsnow** [comment]
On Sun, Nov 8, 2015 at 1:13 PM, Andy Wilson notifications@github.com
wrote:

> I thought we were good to go with regard to community review. See the
> thread on import-us mailing list at:
> https://lists.openstreetmap.org/pipermail/imports-us/2015-September/000722.html
> 
> We do not have city or postcode tags because they were not part of the
> imported dataset.

You might want to join us on the #osm-us irc channel. There seems to be
some issues.

As for the Sep. message, I missed the lack of city and postcode. Did anyone
else mention it?

Clifford

## 

@osm_seattle
osm_seattle.snowandsnow.us
OpenStreetMap: Maps with a human touch

**Comment by wilsaj** [comment]
Alright, I'll hop on osm-us IRC -  thank you for bringing it to our attention

**Comment by almccon** [comment]
I thought that city and postcode were considered optional in OSM, because they are usually easily determined using polygon intersections with admin boundaries, and because they arguably bloat the data.

**Comment by cliffordsnow** [comment]
Alan,
For addresses within a city boundary, the city could easily be looked up.
It is why we don't encourage addr:state tags. But many addresses just
outside of the city limits still show the nearby city. Postcode shapefiles
are best guesses since the UPS doesn't publish zip code boundaries. I've
used Census zipcode shapefiles (ZCTAs) when I'm certain that the boundaries
are clean to add zip codes to data. Unfortunately ZCTAs only give
boundaries. Washington State has produced zipcode tables that include the
city. I wonder if Texas has something similar. Worst case, pull the
zipcodes for Austin and look up the city.

I agree that city and zipcodes do add to the database. Maybe at some point
the data will be separated by layers to keep the database size more
manageable. I can only hope it comes sooner rather than later.

One of these days we need to talk about Bellingham. My friends in
MaptimeSEA are looking for someone else to sponsor their meetup so I can
create one for Skagit, Island, San Juan, and Whatcom Counties.

BTW - I certainly hated to see this import stopped. I hope it doesn't
discourage them from proceeding. I'm a big proponent of importing buildings
and addresses. I believe the quality is much higher than having people
manually enter each address. Plus it would never get done.

Clifford

On Sun, Nov 8, 2015 at 2:26 PM, Alan McConchie notifications@github.com
wrote:

> I thought that city and postcode were considered optional in OSM, because
> they are usually easily determined using polygon intersections with admin
> boundaries, and because they arguably bloat the data.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/atx-osg/atx-buildings/issues/22#issuecomment-154881926
> .

## 

@osm_seattle
osm_seattle.snowandsnow.us
OpenStreetMap: Maps with a human touch

**Comment by wilsaj** [comment]
Looks like we can only infer postcode but not city (see discussion on the imports list: https://lists.openstreetmap.org/pipermail/imports/2015-November/004139.html). We'll go ahead and do that.
