### ISSUE TITLE
building height precision

### ISSUE THREAD

**Issue by wilsaj** [atx-osg/atx-buildings#23]
Trim building height precision - this should have been handled in the data processing scripts already, but sneaky javascript numbers are sneaky.

**Comment by maxerickson** [comment]
Is it likely that the building heights really are accurate to the nearest centimeter? I see hundredths of feet in the source data but that seems more likely to be more an artifact of the process than a statement about the reliability of the measurements.

**Comment by wilsaj** [comment]
Good point. Looks like the metadata only claims vertical accuracy of 2 meters:

> 2012/2013 Orthoimagery collected by Sanborn Mapping Company for the GeoMap consortium. The source imagery used was 6-inch, natural color with an accuracy statement of horizontal positional displacement within +/-3.33 feet of well-defined ground features; accuracy is based on ground control and DEM data. The accuracy statement does not apply to vertical surface features, such as structures, appearing in the digital orthophotography due to inherent lean.
> Building footprints were captured using heads up digitizing methods against the COA supplied 2012/2013 orthoimagery and 2012 Lidar collection series. Each feature was hand digitized and attributed with base of building elevation and nearest (within 2 meters) high point to capture top of building height using the "buildings" feature class from 2012 Lidar dataset.

Maybe we should just round to the nearest integer?

**Comment by maxerickson** [comment]
I wasn't sure how to read that, I think it makes more sense that the 2 meters is referring to how the height was pulled out of the lidar data, somehow describing where they sampled. The Lidar data should be quite reliable, so 2 meters would be a huge uncertainty.

Without knowing more details I would still go with nearest 10 centimeters.

**Comment by wilsaj** [comment]
Agreed - sounds good to me.

**Comment by wilsaj** [comment]
On the imports list Martin Koppenhoefer suggested rounding to cm:

> I would suggest to round it to 1 cm, because 10 cm is something you can already see, and it might cause strange steps in adjacent geometries in some cases (e.g. 6,549 m and 6,551m are really the same height but will result in 6,50 and 6,60 if rounded to 10 cm).

Seems like a good reason. Any thoughts on that @maxerickson?

**Comment by maxerickson** [comment]
Overall I think it's not a big deal.

That said, my preference would be to try to accurately capture/communicate the actual accuracy of the data, not to keep noise because it looks better. Also, given the tendency for detached homes creating that step is not going to happen too often.

I guess I would suggest either going with whatever you think is better or if you want to pursue it, try to find out what someone at the city thinks about the precision of the source data.

**Comment by wilsaj** [comment]
Yeah, we don't need to get silly with precision. In reality most of these buildings have sloped roofs and rendering them as flat at max height would be taking some artistic liberties anyway.

I'll try to get an answer from the city and will update if anything changes. I don't want to block on it though. I'd rather get the import back on track.
