### ISSUE TITLE
Determine how to split up the data for QA

### ISSUE THREAD

**Issue by wilsaj** [atx-osg/atx-buildings#4]
We need to pick a set of boundaries to use to split up the data into smaller sets that can be QA'd and by validated by individuals. Whatever we choose should cover the entire extent of the CoA buildings dataset and be mutually exclusive (no overlapping boundaries). Some proposed methods:
- Zip codes
- Census Tracts
- Census Block Groups
- Census Blocks

**Comment by claysmalley** [comment]
I'd say Census Block Groups are a reasonable size. Not too overwhelmingly large, not too trivially small.

**Comment by wilsaj** [comment]
:+1: - Census Block Groups it is

**Comment by wilsaj** [comment]
Looks good:

![image](https://cloud.githubusercontent.com/assets/303866/9569144/eb079886-4f26-11e5-9112-5afc6981af95.png)
