### ISSUE TITLE
Missing task/census block - south of Palm Valley Blvd

### ISSUE THREAD

**Issue by jseppi** [atx-osg/atx-buildings#41]
West side of Task #761

![image](https://cloud.githubusercontent.com/assets/697848/11446198/43a68728-94f9-11e5-8080-4a6ee0eae7d4.png)

**Comment by wilsaj** [comment]
Actually it looks like this is correct because there aren't any buildings or addresses for the census block groups in this area:

<img width="906" alt="screen shot 2015-12-05 at 10 41 21 am" src="https://cloud.githubusercontent.com/assets/303866/11608908/ecc65e8e-9b3c-11e5-905e-5137b0e28735.png">
